### ISSUE TITLE
Feature: Move URL bar 

### ISSUE THREAD

**Issue by ShalokShalom** [xplosionmind/firefox-monoline#13] opened 2023-09-10 19:39 UTC
Hi there 😃 

Your setup is wonderful, thanks a ton for it. 

I like to move the URL bar to the right side, and I don't really see, how this can be done.

**Comment by xplosionmind** [comment] 2023-10-15 21:29
Hi! This is quite out of scope. Mainly, the problem is that the vast majority of the CSS file would completely change.

I would suggest you to meddle with the CSS yourself and try. 

You are welcome to submit a PR if you want to add comments of things to change in order to align the url bar to the right.

I am closing this issue for now, but I will be happy to reopen it if new contributions tackle this.

**Closed** 2023-10-15 21:30 UTC
Labels: enhancement
